### ISSUE TITLE
Database backups

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-event-service#28]
It is probably a good idea to backup our database somehow. This is the case for crossposting service as well.

**Comment by cooldracula** [comment]
Taking a look at this, I think a good option for us would be [litestream](https://litestream.io), a tool for replicating sqlite databases to an S3 bucket.  We could install it as a systemd service, similar to the existing docker image updates, and replicate to a [digital ocean space](https://cloud.digitalocean.com/spaces), since we are using digital ocean for the droplet itself.  Any new droplet made via ansible scripts has backups enabled by default, so this would give us a to-the-minite backups of the db itself alongside a weekly backup of the entire server if something fully catastrophic happened.

It's fairly straightforward to set up litestream with the services, the only unknown part is doing it via an ansible script.  I'd want to work with the digital ocean api to create a space if needed as part of the script, and don't know the api for spaces at the moment.  Easy enough to figure out though!

**Comment by cooldracula** [comment]
I added an ADR as a pr to our infra repo, here: https://github.com/planetary-social/infrastructure/pull/108

**Comment by cooldracula** [comment]
Am closing this ticket as we have an ADR in review and new tickets related to a new db design that are more relevant for tracking work.
