### ISSUE TITLE
[Event Service] Understand & briefly document how the event and notification services work today

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos-event-service#76]
Review the current event service and document the following:

- What does it do today? 
- How does it do it? 
- How performant is the current event service? Does it meet the benchmarks identified [here](https://www.notion.so/nossocial/Event-service-e9bf29edd1ee475bad269f96a245dab5?pvs=4#295338b80ca04216a98d2b456016ce67)?
- Make a recommendation on the following: 

- - Keep the event service and continue using for notifications
- - Update the event service to make it work better (e.g. it does not grab events in a timely manner etc) 
- - Abandon this event service and use the Primal Event Service instead.
- - Share the results with Linda and Rabble and Matt if he is still around.

**Comment by dcadenas** [comment]
### What does it do today? How does it do it?

The events service can be divided into distinct tasks for a clearer understanding of its functionality:

1. **Saving Relays and Pubkeys in the Local Database:** The foundational building block, upon which all other functions depend, is the discovery and storage of relays and pubkeys in a SQLite3 database. This process begins with a hardcoded list of relays and utilizes a series of time intervals and filters to query the Nostr network. In doing so, it discovers more relays and restarts the process. This enables the identification of events containing new relays and pubkeys. The filters applied are:
    
    - 0: To retrieve pubkeys,
    - 2 (recommended relay): For fetching more relays; however, this kind is deprecated in Nostr,
    - 3 (follow list): To obtain pubkeys along with detailed information about their followers ↔ followees relationships,
    - 10002 (relay list metadata): To acquire more relays.
2. **Special Treatment for Nos App Users' Pubkeys:** Pubkeys associated with Nos app users are treated uniquely and stored separately. For these users, the service analyzes and stores all event types, applying broader filters than those in step 1 for Nos pubkeys. It also collects events where these users are mentioned through p-tags. The nos users pubkeys must first be registered via websocket message. Presently, events of kind 6666, intended for this purpose, are directed to the notifications service rather than the events service. Originating from the Nos app's `registerForNotifications` function, this should probably be renamed as it's also used for the moderation service. Discussions with Matt have included potentially changing the event kind to 30078 to better align with NIPs ([Nostr Improvement Proposals](https://github.com/nostr-protocol/nips/blob/master/78.md)). The advantages of using our own relay as opposed to a websocket are also under consideration.
    
3. **Internal SQL Queue and Publishing:** All events gathered through methods 1 and 2 are channeled into an internal SQL queue. Each entry from this queue is then processed and published to:
    
    - The `nostr-events` Google Cloud PubSub, utilized by our moderation and notifications services. Notably, this PubSub also serves as the endpoint for the notifications service, creating some functional overlap which is currently being analyzed.
    - Our Nostr relay at relay.nos.social.
4. **REST API Exposure:** The events service also features a REST API, that is not currently being used. The API facilitates:
    
    - Accessing the latest 100 events in the database via the `/events` endpoint, which includes an `after` filter for specific event hex IDs.
    - Fetching a specific event ID from the database through the `/events/xxxx` endpoint.
    - Obtaining follower and followee counts for specific public keys, as demonstrated by [this link](https://events.nos.social/public-keys/89ef92b9ebe6dc1e4ea398f6477f227e95429627b0a33dc89b640e137b256be5).


### How performant is the current event service? Does it meet the benchmarks identified [here](https://www.notion.so/nossocial/Event-service-e9bf29edd1ee475bad269f96a245dab5?pvs=4#295338b80ca04216a98d2b456016ce67)?
We are processing around 16 events per second. The mentioned benchmarks are for the notification service which I'm currently inspecting

### Recommendation

The service is functioning well. I find the internal time window task queue useful, although it may need extraction into an independent library at some point for easier understanding and potential reuse. There have been issues with the internal sqlite queue growing too large, but I think it's still too early to consider getting rid of the service based on these instances. There's already a task in place to implement the eviction of old message entries, which could alleviate that specific problem.

The alternative of moving to the Primal solution has the disadvantage of not being under our control, and I currently lack expertise in Julia. The event service can be extended and customized to our needs. There are a few things that I think have overly complicated the code, such as dependency injection and CQRS. While these are nice tools for very large projects, they may be overkill for us.

**Comment by dcadenas** [comment]
## Internals of the nos-notification-service

### Firestore as database
One of the architectural differences with the events service is that data is stored in google firestore through the following collections and subcollections: 

For database details, visit: [Firestore Console](https://console.firebase.google.com/project/nos-notification-service/firestore/data/~2Fevents~2F00000000315803ac1856b386f8b79234e05ec016c9f5a7a682a7dbe272cc4fce)

| Collection Variable Name | Firestore Collection Name | Subcollection of
| ------------------------ | ------------------------- | ---------------- |
| **EventRepo**.collectionEvents | events |  |
| **EventRepo**.collectionEventsNotifications | notifications | Subcollection of events |  |
| **PublicKeyRepo**.collectionPublicKeys | publicKeys |  |  |
| **PublicKeyRepo**.collectionPublicKeysAPNSTokens | apnsTokens | Subcollection of publicKeys |  |
| **RelayRepo**.collectionRelays | relays |  |  |
| **RelayRepo**.collectionRelaysPublicKeys | publicKeys | Subcollection of relays |  |
| **TagRepo**.collectionTags | tags |  |  |
| **TagRepo**.collectionTagsValues | tags | Subcollection of tags |  |
| **TagRepo**.collectionTagsValuesEvents | events | Subcollection of tags/xx/tags |  |

### Inner sub-services:
The server is structured similarly to the events service, were multiple internal functions communicate through queues, either through channels or pubsubs.

#### HTTP Service: Entry point for nos users pubkeys (nos app -> relays + pubkeys + apntokens Firestore DB)

Provides a WebSocket to:
1. Register nos users. This is also present in the events service, although currently, our iOS app only sends messages to this endpoint (see `registerForNotifications`). When a user is registered:
   1. Their relays are stored in the Relays repository, including the pubkey as a subcollection item.
   2. The pubkey is stored through the PublicKeyRepository, including the apnstoken as a subcollection item.

2. Respond to nostr req requests. It seems this is not used by anyone. TODO: Confirm this.

#### Downloader Service: Queries the nostr network (relays + pubkeys DB -> publication to receivedEvent go pubsub)

Maintains a downloader for each relay found in the RelayRepo. Each downloader continuously filters through the described filters, and for each message downloaded, if it's not found in a memory-based cache, it's published to a Go channel "ReceivedEvent" pubsub (GoChannelPubSub, a custom broadcasting channel that sends the message to all subscribers through Go channels).

Downloader filtering:
   The filters used by the downloaders are created from the list of public keys found through the WebSocket registration from the HTTP service, originating from the nos app. We filter for kind 1 note events where we find p tags for these pubkeys. TODO: Should we add more kinds here, such as long notes, etc.?

### ReceivedEvent Subscriber: Saves events to firestore

This is the subscriber side of the previous service. For each event received:

ReceivedEvents subscriptions:
   1. `getEventsHandler`: Subscribes to the queue whenever get requests are made to the WebSocket.
   2. Creates and handles a `SaveReceivedEvent` command: 
      1. Saves the event to the Firestore Event Repository. 
      2. Publishes to the `event_saved` Google Pub/Sub queue for further processing by the next service.

### EventSaved Subscriber: Sends push notifications and pushes to nostr-events pubsub

Subscribes to the `event_saved` Pub/Sub, where messages were sent from the previous service. For each message, it processes a new `NewProcessSavedEvent` command, which, when handled, does the following:
1. Reads the event from the Firestore Event Repository.
2. Saves the event tags into the Firestore Tags Repository.
3. Finds the apnstoken for each p tag mentioned in the event.
4. Creates a push notification and sends it.
5. Saves the notification sent to the notifications subcollection of the events repository.
6. Sends the event to the `nostr-events` Google Pub/Sub. This Pub/Sub feeds the moderation service.

**Comment by dcadenas** [comment]
Full current architecture:

As a first step I'm removing duplication of the event fetching functionality that currently lives in both services. Once this part is done I'll update this diagram with the new state.

![Image](https://github.com/planetary-social/nos-event-service/assets/18184/c725b066-0f35-4e61-9a4b-94f820dfbc05)

**Comment by mplorentz** [comment]
This was very informative. Thanks for the writeup @dcadenas! I added links to this issue from our Notion pages for the Event Service and Notification Service. 

It sounds like your recommendation is to keep the event service, and refactor the notifications service to use it (currently it does not)?

**Comment by dcadenas** [comment]
> It sounds like your recommendation is to keep the event service, and refactor the notifications service to use it (currently it does not)?

That's right. I would really like to have it in Rust but just from a dev perspective because I like the language and I feel more comfortable with it but I believe it would take too much time so I'm leaning more in building future stuff with Rust.
